Repository BangCrush/BankAI-Backend, pull requests merged in 2024-06, with the labels that each got.

#26 Feat: CORS 설정
  src/main/java/com/hana/bankai/global/config/WebMvcConfig.java
  src/main/resources/application.yml
Labels: enhancement

#27 Chore: Account 코드 수정 및 test코드, Product 코드 수정
  src/main/java/com/hana/bankai/domain/product/controller/ProductController.java
  src/main/java/com/hana/bankai/domain/product/service/ProductService.java
Labels: enhancement

#29 Fix: 회원가입 오류 해결
  src/main/java/com/hana/bankai/domain/user/controller/UserController.java
  src/main/java/com/hana/bankai/domain/user/dto/UserRequestDto.java
Labels: bug

#31 Feat: 자동이체
  src/main/java/com/hana/bankai/domain/account/controller/AccountController.java
  src/main/java/com/hana/bankai/domain/account/dto/AccountRequestDto.java
  src/main/java/com/hana/bankai/domain/account/repository/AccountRepository.java
  src/main/java/com/hana/bankai/domain/account/service/AccountService.java
  src/main/java/com/hana/bankai/domain/autotransfer/entity/AutoTransfer.java
  src/main/java/com/hana/bankai/domain/autotransfer/entity/AutoTransferId.java
  src/main/java/com/hana/bankai/domain/autotransfer/repository/AutoTransferRepository.java
  src/main/java/com/hana/bankai/domain/autotransfer/service/AutoTransferService.java
  src/main/java/com/hana/bankai/global/scheduler/BankaiScheduler.java
Labels: enhancement

#32 [feat] JWT 토큰 기반 사용자 인증, 인가 error handling
  src/main/java/com/hana/bankai/domain/product/controller/ProductController.java
  src/main/java/com/hana/bankai/domain/user/controller/UserController.java
  src/main/java/com/hana/bankai/global/error/ErrorCode.java
  src/main/java/com/hana/bankai/global/security/SecurityConfig.java
  src/main/java/com/hana/bankai/global/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/hana/bankai/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/hana/bankai/global/security/jwt/JwtAuthenticationFilter.java
Labels: enhancement

#33 Feat: jwt token 재발급
  src/main/java/com/hana/bankai/domain/user/controller/UserController.java
  src/main/java/com/hana/bankai/domain/user/service/UserService.java
  src/main/java/com/hana/bankai/global/common/response/SuccessCode.java
  src/main/java/com/hana/bankai/global/error/ErrorCode.java
  src/main/java/com/hana/bankai/global/security/SecurityConfig.java
  src/main/java/com/hana/bankai/global/security/jwt/JwtTokenProvider.java
Labels: enhancement

#35 Feat: 상품 키워드 검색 및 Account 코드 재수정,상품 top3 로직 수정, ProductResponseDto, ProductService 코드 간결화 (from사용)
  src/main/java/com/hana/bankai/domain/account/dto/AccountRequestDto.java
  src/main/java/com/hana/bankai/domain/account/entity/Account.java
  src/main/java/com/hana/bankai/domain/account/repository/AccountRepository.java
  src/main/java/com/hana/bankai/domain/account/service/AccountService.java
  src/main/java/com/hana/bankai/domain/product/controller/ProductController.java
  src/main/java/com/hana/bankai/domain/product/dto/ProductRequestDto.java
  src/main/java/com/hana/bankai/domain/product/dto/ProductResponseDto.java
  src/main/java/com/hana/bankai/domain/product/repsoitory/ProductRepository.java
  src/main/java/com/hana/bankai/domain/product/service/ProductService.java
Labels: enhancement

#37 Chore: 상품 전체 조회 예외처리 추가
  src/main/java/com/hana/bankai/domain/product/service/ProductService.java
Labels: enhancement

#38 Chore: 회원가입 여부 확인 입력 데이터 변경 등
  src/main/java/com/hana/bankai/domain/account/entity/Account.java
  src/main/java/com/hana/bankai/domain/account/service/AccountService.java
  src/main/java/com/hana/bankai/domain/user/controller/UserController.java
  src/main/java/com/hana/bankai/domain/user/dto/UserRequestDto.java
  src/main/java/com/hana/bankai/domain/user/repository/UserRepository.java
  src/main/java/com/hana/bankai/domain/user/service/MailService.java
  src/main/java/com/hana/bankai/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: enhancement

#39 Feat: 사용자 총 자산 조회 시 반환값 수정 - 이름 추가
  src/main/java/com/hana/bankai/domain/account/dto/AccountResponseDto.java
  src/main/java/com/hana/bankai/domain/account/service/AccountService.java
Labels: enhancement

#43 Feat: 휴대폰 본인인증 SMS 기능 구현
  build.gradle
  src/main/java/com/hana/bankai/domain/user/controller/UserController.java
  src/main/java/com/hana/bankai/domain/user/dto/UserRequestDto.java
  src/main/java/com/hana/bankai/domain/user/repository/SmsCertification.java
  src/main/java/com/hana/bankai/domain/user/service/UserService.java
  src/main/java/com/hana/bankai/domain/user/util/SmsUtil.java
  src/main/java/com/hana/bankai/global/common/response/SuccessCode.java
  src/main/java/com/hana/bankai/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: enhancement

#44 Fix: 계좌생성(상품가입) amount = null 입력 문제 해결 등
  src/main/java/com/hana/bankai/domain/account/controller/AccountController.java
  src/main/java/com/hana/bankai/domain/account/service/AccountService.java
  src/main/java/com/hana/bankai/domain/autotransfer/service/AutoTransferService.java
Labels: refactor

#45 Feat : 입출금 이자 구현, 이자지급 Enum 추가
  src/main/java/com/hana/bankai/domain/account/repository/AccountRepository.java
  src/main/java/com/hana/bankai/domain/account/service/AccountService.java
  src/main/java/com/hana/bankai/domain/accounthistory/entity/HisType.java
  src/main/java/com/hana/bankai/global/error/ErrorCode.java
  src/main/java/com/hana/bankai/global/scheduler/BankaiScheduler.java
Labels: enhancement

#46 Fix : Test code 주석처리
  src/test/java/com/hana/bankai/account/AccountInsertTest.java
Labels: enhancement

#47 Fix : Test code 주석처리
  src/test/java/com/hana/bankai/scheduler/SchedulerTest.java
Labels: enhancement

#48 Chore: AWS Secrets Manager 삭제
  build.gradle
  src/main/resources/bootstrap.yml
  src/test/java/com/hana/bankai/account/AccTransferTest.java
Labels: enhancement

#49 Chore: 자동이체 설정 수정-대출 상품 제외
  src/main/java/com/hana/bankai/domain/account/service/AccountService.java
Labels: bug

#51 Refactor: AccountService 리팩토링
  src/main/java/com/hana/bankai/domain/account/service/AccountService.java
  src/main/java/com/hana/bankai/global/error/ErrorCode.java
Labels: refactor

#53 Feat: Admin 초기 세팅
  src/main/java/com/hana/bankai/domain/admin/controller/AdminController.java
  src/main/java/com/hana/bankai/domain/admin/service/AdminService.java
Labels: enhancement

#54 Chore : Product 전체,type별 조회 dto 수정 및 로직 수정 - 2
  src/main/java/com/hana/bankai/domain/product/controller/ProductController.java
  src/main/java/com/hana/bankai/domain/product/dto/ProductResponseDto.java
  src/main/java/com/hana/bankai/domain/product/service/ProductService.java
Labels: enhancement

#57 Feat: Admin line chart 데이터
  src/main/java/com/hana/bankai/domain/account/repository/AccountRepository.java
  src/main/java/com/hana/bankai/domain/admin/controller/AdminController.java
  src/main/java/com/hana/bankai/domain/admin/service/AdminService.java
  src/main/java/com/hana/bankai/global/security/SecurityConfig.java
Labels: enhancement

#58 Feat: admin page 막대 그래프 API
  src/main/java/com/hana/bankai/domain/account/entity/Account.java
  src/main/java/com/hana/bankai/domain/admin/controller/AdminController.java
  src/main/java/com/hana/bankai/domain/admin/dto/AdminResponseDto.java
  src/main/java/com/hana/bankai/domain/admin/entity/JoinCnt.java
  src/main/java/com/hana/bankai/domain/admin/service/AdminService.java
  src/main/java/com/hana/bankai/domain/product/controller/ProductController.java
  src/main/java/com/hana/bankai/domain/product/dto/ProductResponseDto.java
  src/main/java/com/hana/bankai/domain/product/entity/Product.java
  src/main/java/com/hana/bankai/domain/product/repsoitory/ProductRepository.java
  src/main/java/com/hana/bankai/domain/product/service/ProductService.java
  src/main/java/com/hana/bankai/global/security/SecurityConfig.java
Labels: enhancement

#60 Fix : 사용하지 않는 import문 제거
  src/main/java/com/hana/bankai/domain/admin/controller/AdminController.java
  src/main/java/com/hana/bankai/domain/admin/service/AdminService.java
Labels: bug

#61 Feat : 이체 시 적금,예금 일 경우 예외 처리 케이스 추가 및 ErrorCode 추가
  src/main/java/com/hana/bankai/domain/account/service/AccountService.java
  src/main/java/com/hana/bankai/domain/autotransfer/service/AutoTransferService.java
  src/main/java/com/hana/bankai/global/error/ErrorCode.java
Labels: enhancement

#62 Chore : 회원정보 조회 Dto에 메인계좌 변수추가
  src/main/java/com/hana/bankai/domain/user/dto/UserResponseDto.java
Labels: enhancement

#63 [feat] 관리자 페이지 시큐리티 적용
  src/main/java/com/hana/bankai/domain/admin/controller/AdminController.java
  src/main/java/com/hana/bankai/global/security/SecurityConfig.java
Labels: enhancement

#64 Refactor: 사용자 정보 조회, 상품 조회 반환 데이터 수정
  src/main/java/com/hana/bankai/domain/product/dto/ProductResponseDto.java
  src/main/java/com/hana/bankai/domain/user/dto/UserResponseDto.java
Labels: refactor

#65 Fix: User 칼럼 형식 수정
  src/main/java/com/hana/bankai/domain/user/entity/User.java
Labels: bug

#67 Fix: 계좌이체 시 입금 동시성 문제 해결
  src/main/java/com/hana/bankai/domain/account/service/AccountService.java
  src/main/java/com/hana/bankai/global/aop/DistributedLock.java
  src/main/java/com/hana/bankai/global/aop/DistributedLockAop.java
  src/test/java/com/hana/bankai/account/AccTransferTest.java
Labels: bug

#68 Refactor: 계좌 로그 target 수정-이자 지급 고려
  src/main/java/com/hana/bankai/domain/accounthistory/service/AccHisService.java
Labels: refactor

#69 Chore: 스케줄러 작동 시간 변경
  src/main/java/com/hana/bankai/global/scheduler/BankaiScheduler.java
Labels: refactor

#71 Feat: 사용자 일일 이체 금액 확인
  src/main/java/com/hana/bankai/domain/user/controller/UserController.java
  src/main/java/com/hana/bankai/domain/user/service/UserService.java
  src/main/java/com/hana/bankai/domain/user/util/SmsUtil.java
  src/main/java/com/hana/bankai/global/common/response/SuccessCode.java
Labels: enhancement

#74 Feat: 당일 이체 가능한 금액 확인
  src/main/java/com/hana/bankai/domain/user/controller/UserController.java
  src/main/java/com/hana/bankai/domain/user/service/UserService.java
Labels: enhancement
